<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jet</string>
		<string>javajet</string>
	</array>
	<key>name</key>
	<string>JET</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%=</string>
			<key>contentName</key>
			<string>text.source.jet</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>support.class.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%@</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.text.directive.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#directive.jet</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%=</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.text.expression.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.text.scriptlet.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>.*?</string>
			<key>name</key>
			<string>source.text.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>directive.jet</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jet</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(jet|package|class|imports|startTag|endTag|skeleton|nlString|include|fail)\b</string>
		</dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.jet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.jet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.jet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.jet</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jet</string>
	<key>uuid</key>
	<string>4FFA9E40-1C7C-4097-9F1B-AADEA03DD5AF</string>
</dict>
</plist>
